# Generated by Django 3.2.9 on 2022-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_account_nr_patentu_strzeleckiego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='adres',
            field=models.TextField(default='None', verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='account',
            name='kod_poczowy',
            field=models.TextField(default='None', verbose_name='Kod kod_poczowy'),
        ),
    ]
