# Generated by Django 3.2.9 on 2022-11-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20221115_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nr_telefonu',
            field=models.TextField(default='None', verbose_name='Numer telefonu'),
        ),
    ]
