# Generated by Django 3.2.9 on 2022-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_account_nr_telefonu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Użytkownik'},
        ),
        migrations.AlterField(
            model_name='account',
            name='imie',
            field=models.TextField(max_length=60, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='account',
            name='klub',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Klub'),
        ),
        migrations.AlterField(
            model_name='account',
            name='kod_poczowy',
            field=models.TextField(default='None', verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='account',
            name='nazwisko',
            field=models.TextField(max_length=60, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Username'),
        ),
    ]
