# Generated by Django 3.2.9 on 2022-11-10 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_forumpost_forumtopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.forumtopic', verbose_name='Temat'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='topic',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Temat'),
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='Treść')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.forumpost', verbose_name='post')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
