# Generated by Django 3.2.9 on 2022-12-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20221215_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltspayment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ltspayment',
            name='sessionid',
            field=models.CharField(default='defval', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ltspayment',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
