# Generated by Django 3.2.9 on 2022-12-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20221215_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltspayment',
            name='orderid',
            field=models.IntegerField(null=True),
        ),
    ]
